### Pandas series
Series is like a column

In [15]:
import pandas as pd 
a = [1,4,5]
myvar = pd.Series(a)
print(myvar)

0    1
1    4
2    5
dtype: int64

### Labels

In [16]:
print(myvar[2])

5

### Creating lables

In [17]:
import pandas as pd
a = [1, 7, 2]
myvar = pd.Series(a, index = ["x", "y", "z"])
print(myvar)

x    1
y    7
z    2
dtype: int64

In [18]:
print(myvar["z"])

2

### Key/value object as series

In [19]:
import pandas as pd 
calories = {"day1": 890, "day2": 432, "day3": 999}
myvar = pd.Series(calories)
print(myvar)

day1    890
day2    432
day3    999
dtype: int64

In [20]:
import pandas as pd 
calories = {"day1": 232, "day2": 234, "day3": 987}
myvar = pd.Series(calories, index= ["day1", "day2"])
print(myvar["day2"])

234

### Dataframes
 Data sets in Pandas are usually multi-dimensional tables

In [21]:
import pandas as pd 
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45

In [22]:
import pandas as pd 
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar["duration"])

0    50
1    40
2    45
Name: duration, dtype: int64

In [23]:
print(myvar.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [24]:
print(myvar.iloc[2])

calories    390
duration     45
Name: 2, dtype: int64

At first loc and iloc looks same but they are different. loc think location by name and iloc think integer location. EX:

In [25]:
myvar.index =["a", "b", "c"]
print(myvar)

   calories  duration
a       420        50
b       380        40
c       390        45

In [ ]:
myvar.loc[["a"]] # you can also use like this myvar.loc["a"]

   calories  duration
a       420        50

In [40]:
print(myvar.loc[0])

KeyError: 0

👆🏻It will show error in loc. Why? Because there is no label named 0 anymore.

In [ ]:
print(myvar.iloc[0])

calories    420
duration     50
Name: a, dtype: int64

👆🏻 It will work beacause 0 is the first position.

In [ ]:
print(myvar.loc["c"])

calories    390
duration     45
Name: c, dtype: int64

#### Read CSV Files

In [ ]:
myvar = pd.read_csv("friends.csv")

viewing first 5 rows

In [ ]:
print(myvar.head)

<bound method NDFrame.head of    Unnamed: 0    name  marks     city
0           0     mia     92    paris
1           1    maya     34  america
2           2  viktor     82      NYC
3           3    john     97       LA>

viewing last 5 rows

In [ ]:
print(myvar.tail())

   Unnamed: 0    name  marks     city
0           0     mia     92    paris
1           1    maya     34  america
2           2  viktor     82      NYC
3           3    john     97       LA

In [ ]:
print(myvar.info)

<bound method DataFrame.info of    Unnamed: 0    name  marks     city
0           0     mia     92    paris
1           1    maya     34  america
2           2  viktor     82      NYC
3           3    john     97       LA>

In [ ]:
print(myvar.describe())

       Unnamed: 0      marks
count    4.000000   4.000000
mean     1.500000  76.250000
std      1.290994  28.848743
min      0.000000  34.000000
25%      0.750000  70.000000
50%      1.500000  87.000000
75%      2.250000  93.250000
max      3.000000  97.000000

In [ ]:
import pandas as pd
data = {
  "Name" : ["John", "Anna", "Peter", "Linda"],
  "Location" : ["New York", "Paris", "Berlin", "London"],
  "Age" : [24, 13, 53, 33]
}

df = pd.DataFrame(data)
filtered = df[df["Age"]>20]
print(filtered)

    Name  Location  Age
0   John  New York   24
2  Peter    Berlin   53
3  Linda    London   33

In [ ]:
filtered = df[df["Location"] != "India"]
print(filtered)

    Name  Location  Age
0   John  New York   24
1   Anna     Paris   13
2  Peter    Berlin   53
3  Linda    London   33

multiple conditions

In [ ]:
filtered = df[(df["Name"] == "Anna") & (df["Age"] > 30)]
print(filtered)

Empty DataFrame
Columns: [Name, Location, Age]
Index: []

adding new column

In [ ]:
df["Marks"] = [85, 92, 78, 90]
print(df)

    Name  Age Location  Marks
0   John   24       NY     85
1   Anna   13    Paris     92
2  Peter   53   Berlin     78
3  Linda   33   London     90

In [ ]:
df.loc[0, "Marks"] = 95
print(df)

    Name  Age Location  Marks
0   John   24       NY     95
1   Anna   13    Paris     92
2  Peter   53   Berlin     78
3  Linda   33   London     90

In [ ]:
print(df.columns)

Index(['Name', 'Age', 'Marks'], dtype='object')

In [ ]:
df["Location"] = ["NY", "Paris", "Berlin", "London"]

In [ ]:
print(df.columns)

Index(['Name', 'Age', 'Location', 'Marks'], dtype='object')

In [ ]:
df.drop("Marks", axis=1, inplace=True)
print(df)

    Name  Age Location
0   John   24       NY
1   Anna   13    Paris
2  Peter   53   Berlin
3  Linda   33   London

### Handling missing values
#### Check missing values

In [ ]:
print(df.isna())

NameError: name 'df' is not defined

#### Remove Missing Values

In [ ]:
df.dropna()

    Name  Age Location
0   John   24       NY
1   Anna   13    Paris
2  Peter   53   Berlin
3  Linda   33   London

In [ ]:
df["Gender"] = ["M", "F", "M", "F"]
print(df)

    Name  Location  Age Gender
0   John  New York   24      M
1   Anna     Paris   13      F
2  Peter    Berlin   53      M
3  Linda    London   33      F

In [ ]:
df[df["Age"]>20]

    Name  Location  Age Gender
0   John  New York   24      M
2  Peter    Berlin   53      M
3  Linda    London   33      F

In [ ]:
df.query("Age > 20 and Gender == 'M'")

    Name  Location  Age Gender
0   John  New York   24      M
2  Peter    Berlin   53      M

In [ ]:
df["Age_plus_10"] = df["Age"].apply(lambda x: x + 10)
print(df)

    Name  Location  Age Gender  Age_plus_10
0   John  New York   24      M           34
1   Anna     Paris   13      F           23
2  Peter    Berlin   53      M           63
3  Linda    London   33      F           43

#### Fill Missing Values

In [ ]:
df.fillna(0)

    Name  Age Location
0   John   24       NY
1   Anna   13    Paris
2  Peter   53   Berlin
3  Linda   33   London

### Sorting data
#### SORT BY AGE

In [ ]:
df.sort_values("Age", ascending=True)

    Name  Age Location
1   Anna   13    Paris
0   John   24       NY
3  Linda   33   London
2  Peter   53   Berlin

### GroupBy

In [ ]:
data = {
    "Department": ["IT", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 45000, 47000]
}

df = pd.DataFrame(data)

print(df.groupby("Department").median())

             Salary
Department
HR          46000.0
IT          55000.0